SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR, TO_CHAR(SALES_DATE, 'MM') AS MONTH, U.GENDER AS GENDER, COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
USING(USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), GENDER
ORDER BY YEAR, MONTH, GENDER;