SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES AS FAVORITES, ADDRESS, ROUND(AVG(NVL(REVIEW_SCORE, 0)), 2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R
USING(REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;