SELECT CART_ID
FROM (SELECT CART_ID
      FROM CART_PRODUCTS
      WHERE NAME = 'Yogurt'
      GROUP BY CART_ID)
      JOIN (SELECT CART_ID
            FROM CART_PRODUCTS
            WHERE NAME = 'Milk'
            GROUP BY CART_ID)
      USING(CART_ID)
ORDER BY CART_ID;