SELECT FLAVOR
FROM (SELECT FLAVOR
      FROM
      (SELECT *
       FROM JULY
       UNION
       SELECT *
       FROM FIRST_HALF)
      GROUP BY FLAVOR
      ORDER BY SUM(TOTAL_ORDER) DESC)
WHERE ROWNUM < 4;