SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P
USING(PT_NO)
JOIN DOCTOR D
ON(MDDR_ID = DR_ID)
WHERE TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13' AND A.MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD;