# Generated by Django 4.1.1 on 2022-09-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoFacility',
            fields=[
                ('cf_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=30)),
                ('fac_popu', models.BigIntegerField(blank=True, null=True)),
                ('qur_rate', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'co_facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoPopuDensity',
            fields=[
                ('cp_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=30)),
                ('popu_density', models.BigIntegerField(blank=True, null=True)),
                ('qur_rate', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'co_popu_density',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoVaccine',
            fields=[
                ('cv_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=30)),
                ('v1th_rate', models.BigIntegerField(blank=True, null=True)),
                ('v2th_rate', models.BigIntegerField(blank=True, null=True)),
                ('v3th_rate', models.BigIntegerField(blank=True, null=True)),
                ('v4th_rate', models.BigIntegerField(blank=True, null=True)),
                ('qur_rate', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'co_vaccine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoWeekday',
            fields=[
                ('cw_idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('sun', models.BigIntegerField(blank=True, null=True)),
                ('mon', models.BigIntegerField(blank=True, null=True)),
                ('tue', models.BigIntegerField(blank=True, null=True)),
                ('wed', models.BigIntegerField(blank=True, null=True)),
                ('thu', models.BigIntegerField(blank=True, null=True)),
                ('fri', models.BigIntegerField(blank=True, null=True)),
                ('sat', models.BigIntegerField(blank=True, null=True)),
                ('std_day', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'co_weekday',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
    ]
