CREATE FUNCTION getNthHighestSalary(N IN NUMBER) RETURN NUMBER IS
result NUMBER;
BEGIN
    /* Write your PL/SQL query statement below */
    SELECT SALARY
    INTO RESULT
    FROM (SELECT DISTINCT(SALARY), RANK() OVER (ORDER BY SALARY DESC) AS RANKING
          FROM EMPLOYEE GROUP BY SALARY)
    WHERE RANKING = N;
    RETURN result;
END;