SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM(SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY,
            DENSE_RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RANK
     FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID) T
WHERE T.RANK < 4
ORDER BY DEPARTMENT, SALARY DESC;